/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.BlPlan;
import bl.BlRefreshclassandteacher;
import bl.BlTableLoad;
import data.Klasse;
import data.Lehrer;
import data.Stunde;
import data.StundeBau;
import data.Var;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author timon_kaufmann
 */
public class DeleteDlg extends javax.swing.JDialog {

    /**
     * Creates new form EntryDlg
     */


    public DeleteDlg(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        BlRefreshclassandteacher.refreshlistteacher();

    }
    public static boolean ok = false;
    public static boolean open = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tffach = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfklasse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfuhrbis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfuhrvon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("Fach");
        jPanel1.add(jLabel1);
        jPanel1.add(tffach);

        jLabel2.setText("Klasse");
        jPanel1.add(jLabel2);
        jPanel1.add(tfklasse);

        jLabel7.setText("Uhrzeit von");
        jPanel1.add(jLabel7);
        jPanel1.add(tfuhrbis);

        jLabel8.setText("Uhrzeit bis");
        jPanel1.add(jLabel8);
        jPanel1.add(tfuhrvon);

        jLabel5.setText("Tag");
        jPanel1.add(jLabel5);
        jPanel1.add(tfTag);

        jButton1.setIcon(data.Var.imageIconok);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_fertig(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setIcon(data.Var.imageIconnotok);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_abbruch(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void on_fertig(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_fertig
        Stunde del = null;
        for (Stunde stunde : data.Var.hour) {
            if(stunde.getFach().equals(tffach.getText())&&stunde.getKlasse().equals(tfklasse.getText())&&stunde.getUhrzeitvon().equals(tfuhrvon.getText())&&stunde.getTag().equals(tfTag.getText())){
                del = stunde;
            }
        }
        data.Var.hour.remove(del);

        BlTableLoad.firstload();
        BlTableLoad.akttable(tfklasse.getText());
        open = false;
        bl.BlRefreshclassandteacher.refreshlistteacher();
        bl.BlRefreshclassandteacher.refreshlistcombpteacher();
        this.dispose();
    }//GEN-LAST:event_on_fertig

    private void on_abbruch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_abbruch
        ok = false;
        open = false;
        bl.BlRefreshclassandteacher.refreshlistteacher();
        bl.BlRefreshclassandteacher.refreshlistcombpteacher();
        this.dispose();
    }//GEN-LAST:event_on_abbruch


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfTag;
    private javax.swing.JTextField tffach;
    private javax.swing.JTextField tfklasse;
    private javax.swing.JTextField tfuhrbis;
    private javax.swing.JTextField tfuhrvon;
    // End of variables declaration//GEN-END:variables
}
