/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Klasse;
import data.Lehrer;
import data.Stunde;
import data.Var;

/**
 *
 * @author timon_kaufmann
 */
public class LehrerDlg extends javax.swing.JDialog {

    /**
     * Creates new form EntryDlg
     *
     * @param parent
     * @param modal
     */
    public LehrerDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
    public LehrerDlg(java.awt.Frame parent, boolean modal, Lehrer l) {
        super(parent, modal);
        initComponents();
        tfkuerzel.setText(l.getKuerzel());
        tfname.setText(l.getName());
        tfwochenstunden.setText(l.getWochenstunden()+"");
        jButton2.setVisible(false);
    }
    public static boolean ok = true;
    public static boolean open = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfkuerzel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfwochenstunden = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel2.setText("Name");
        jPanel1.add(jLabel2);

        tfname.setText("Lukas");
        jPanel1.add(tfname);

        jLabel3.setText("Kürzel");
        jPanel1.add(jLabel3);

        tfkuerzel.setText("Patter");
        jPanel1.add(tfkuerzel);

        jLabel1.setText("Wochenstunden:");
        jPanel1.add(jLabel1);

        tfwochenstunden.setText("25");
        jPanel1.add(tfwochenstunden);

        jButton1.setIcon(data.Var.imageIconok);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_fertig(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setIcon(data.Var.imageIconnotok);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_abbruch(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void on_abbruch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_abbruch
        ok = false;
        open = false;
        this.dispose();
    }//GEN-LAST:event_on_abbruch

    private void on_fertig(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_fertig
        ok = true;
        Lehrer l = new Lehrer(tfname.getText(), tfkuerzel.getText(), Integer.parseInt(tfwochenstunden.getText()), true);
        data.Var.lehrer.add(l);
        System.out.println(data.Var.lehrer.toString());
        bl.BlRefreshclassandteacher.refreshlistteacher();
        bl.BlRefreshclassandteacher.refreshlistcombpteacher();
        
        open = false;
        this.dispose();
    }//GEN-LAST:event_on_fertig

    /**
     * @param args the command line arguments
     */
    public static boolean isOk() {
        return ok;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfkuerzel;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfwochenstunden;
    // End of variables declaration//GEN-END:variables
}
