/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import buttonbl.ButtonEditor;
import buttonbl.ButtonRenderer;
import buttonbl.ButtonRendererAbwesend;
import java.awt.event.MouseEvent;
import javax.swing.JCheckBox;

/**
 *
 * @author lukas
 */
public class LehrerDllMain extends javax.swing.JDialog {

    /**
     * Creates new form LehrerDllMain
     */ 
    LehrerDlg lehrerdlg = new LehrerDlg(null,false);
    public LehrerDllMain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         tabelle.setFillsViewportHeight(true);
        tabelle.getColumn("Anwesend").setCellRenderer(new ButtonRenderer());
        tabelle.getColumn("Anwesend").setCellEditor(new ButtonEditor(new JCheckBox()));
        tabelle.getColumn("Abwesend").setCellRenderer(new ButtonRendererAbwesend());
        tabelle.getColumn("Abwesend").setCellEditor(new ButtonEditor(new JCheckBox()));
        tabelle.setRowHeight(22);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menutabelle1 = new javax.swing.JPopupMenu();
        Adden1 = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelle = new javax.swing.JTable();

        Adden1.setText("Lehrer hinzufügen");
        Adden1.setToolTipText("");
        Adden1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adden1Tabelle1adden(evt);
            }
        });
        menutabelle1.add(Adden1);

        Delete.setText("Lehrer löschen");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDeleteBestellung(evt);
            }
        });
        menutabelle1.add(Delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vorname", "Nachname", "Anwesend", "Abwesend"
            }
        ));
        tabelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelleMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            this.menutabelle1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tabelleMouseClicked

    private void Adden1Tabelle1adden(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adden1Tabelle1adden
        try {
            lehrerdlg = new LehrerDlg(null, true);
            if(lehrerdlg.isOk())
            {
                lehrerdlg.setVisible(true);
                //tableModel.tableDataChanged();
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_Adden1Tabelle1adden

    private void DeleteDeleteBestellung(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDeleteBestellung
        //        try {
            //            int index = bestellTabelle.getSelectedRow();
            //            Bestellungen best = tableModel.getBest(index);
            //            int id = best.getId();
            //            tableModel.delete(index);
            //            access.DeleteBestellung(id);
            //            List<Bestellungen> test = tableModel.getDatensaetze();
            //            if(test.size()==0)
            //            {
                //                access.SetIDBestellungauf1();
                //            }
            //        } catch (Exception e) {
            //            e.getMessage();
            //        }
    }//GEN-LAST:event_DeleteDeleteBestellung

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LehrerDllMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LehrerDllMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LehrerDllMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LehrerDllMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LehrerDllMain dialog = new LehrerDllMain(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Adden1;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu menutabelle1;
    private javax.swing.JTable tabelle;
    // End of variables declaration//GEN-END:variables
}
