package gui;

import bl.BlModelPlan;
import bl.BlTableLoad;
import bl.JTCellRenderer;
import bl.TableRenderer;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import static com.sun.source.doctree.AttributeTree.ValueKind.SINGLE;
import data.Klasse;
import data.ModelData;
import data.Stunde;
import data.StundeAnsicht;
import data.Var;
import data.Zeit;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lukas Grafoner
 */
public class PlanDlg extends javax.swing.JDialog {

    /**
     * Creates new form PlanDlg
     */
    private boolean klasseoderlehrer;
    KlasseDlg klassedlg = new KlasseDlg(null, false);
    LehrerDlg lehrerdlg = new LehrerDlg(null, false);
    public static DefaultListModel listenModellClasse = new DefaultListModel();
    public static DefaultListModel listenModellTeacher = new DefaultListModel();

    //TableRenderer render = new TableRenderer();
    JTCellRenderer render = new JTCellRenderer();

    public PlanDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        klasseoderlehrer = true;
        jPanel3.setVisible(false);
        table.getTableHeader().setReorderingAllowed(false);
        list.setSelectionMode(SINGLE_SELECTION);
        list.setModel(listenModellClasse);
        table.setModel(data.Var.m);
        table.setDefaultRenderer(Object.class, render);
        table.setRowHeight(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menutabelle1 = new javax.swing.JPopupMenu();
        Adden1 = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        menutabelle2 = new javax.swing.JPopupMenu();
        Adden2 = new javax.swing.JMenuItem();
        Delete1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();
        label16 = new javax.swing.JLabel();
        label17 = new javax.swing.JLabel();
        label18 = new javax.swing.JLabel();
        label19 = new javax.swing.JLabel();
        label20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menustundenzeiten = new javax.swing.JMenuItem();
        menulehrerbea = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        tabelleladen = new javax.swing.JMenuItem();

        Adden1.setText("Klasse hinzufügen");
        Adden1.setToolTipText("");
        Adden1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adden1Tabelle1adden(evt);
            }
        });
        menutabelle1.add(Adden1);

        Delete.setText("Klasse löschen");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDeleteBestellung(evt);
            }
        });
        menutabelle1.add(Delete);

        Adden2.setText("Lehrer hinzufügen");
        Adden2.setToolTipText("");
        Adden2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adden2Tabelle1adden(evt);
            }
        });
        menutabelle2.add(Adden2);

        Delete1.setText("Lehrer löschen");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1DeleteBestellung(evt);
            }
        });
        menutabelle2.add(Delete1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                on_load(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(259, 50));

        list.setBorder(javax.swing.BorderFactory.createTitledBorder("Klassen"));
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1AHIF" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                on_mouseclicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);
        list.getAccessibleContext().setAccessibleDescription("");

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.WEST);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null},
                {"", null, null, "", null, null, null, null},
                {"", null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null}
            },
            new String [] {
                "Stunde", "Von", "Bis", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 6));

        ImageIcon imageIcon5 = new ImageIcon("src\\main\\java\\resource\\klassen_auswahl.png"); // load the image to a imageIcon
        Image image5 = imageIcon5.getImage(); // transform it
        Image newimg5 = image5.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon5 = new ImageIcon(newimg5);  // transform it back
        jButton5.setIcon(imageIcon5);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        ImageIcon imageIcon4 = new ImageIcon("src\\main\\java\\resource\\lehrer_auswahl.png"); // load the image to a imageIcon
        Image image4 = imageIcon4.getImage(); // transform it
        Image newimg4 = image4.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon4 = new ImageIcon(newimg4);  // transform it back
        jButton4.setIcon(imageIcon4);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        ImageIcon imageIcon3 = new ImageIcon("src\\main\\java\\resource\\bearbeiten_auswahl.png"); // load the image to a imageIcon
        Image image3 = imageIcon3.getImage(); // transform it
        Image newimg3 = image3.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon3 = new ImageIcon(newimg3);  // transform it back
        jButton3.setIcon(imageIcon3);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jPanel1.add(jLabel2);
        jPanel1.add(jLabel3);
        jPanel1.add(jLabel4);
        jPanel1.add(jLabel5);
        jPanel1.add(jLabel6);
        jPanel1.add(jLabel7);
        jPanel1.add(jLabel8);
        jPanel1.add(jLabel9);
        jPanel1.add(jLabel10);
        jPanel1.add(jLabel12);
        jPanel1.add(jLabel13);
        jPanel1.add(jLabel14);
        jPanel1.add(jLabel15);
        jPanel1.add(jLabel1);
        jPanel1.add(jLabel11);

        ImageIcon imageIcon2 = new ImageIcon("src\\main\\java\\resource\\speichern_auswahl.png"); // load the image to a imageIcon
        Image image2 = imageIcon2.getImage(); // transform it
        Image newimg2 = image2.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon2 = new ImageIcon(newimg2);  // transform it back
        jButton1.setIcon(imageIcon2);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        ImageIcon imageIcon = new ImageIcon("src\\main\\java\\resource\\drucken_auswahl.png"); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);  // transform it back
        jButton2.setIcon(imageIcon);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fächer"));
        jPanel3.setLayout(new java.awt.GridLayout(2, 6));

        label.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\me_1.png"));
        label.setText("ME");
        label.setToolTipText("");
        label.setOpaque(true);
        label.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label);

        label2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\bsp_1.png"));
        label2.setText("BSP");
        label2.setToolTipText("");
        label2.setOpaque(true);
        label2.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label2);

        label3.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\we_1.png"));
        label3.setText("Werken");
        label3.setToolTipText("");
        label3.setOpaque(true);
        label3.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label3);

        label4.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\fu_1.png"));
        label4.setText("FU");
        label4.setToolTipText("");
        label4.setOpaque(true);
        label4.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label4);

        label5.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\daz_1.png"));
        label5.setText("DAZ");
        label5.setToolTipText("");
        label5.setOpaque(true);
        label5.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label5);

        label9.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\glz_1.png"));
        label9.setText("GLZ");
        label9.setToolTipText("");
        label9.setOpaque(true);
        label9.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label9);

        label11.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\chor_1.png"));
        label11.setText("Chor");
        jPanel3.add(label11);

        label12.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label12.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\e_1.png"));
        label12.setText("E");
        jPanel3.add(label12);

        label13.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label13.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\ge_1.png"));
        label13.setText("gE");
        label13.setToolTipText("");
        label13.setOpaque(true);
        label13.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label13);

        label14.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label14.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\rk_1.png"));
        label14.setText("RK");
        label14.setToolTipText("");
        label14.setOpaque(true);
        label14.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label14);

        label15.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label15.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\se_1.png"));
        label15.setText("SE");
        label15.setToolTipText("");
        label15.setOpaque(true);
        label15.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label15);

        label16.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\spf_1.png"));
        label16.setText("SPF");
        label16.setToolTipText("");
        label16.setOpaque(true);
        label16.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label16);

        label17.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\sphl_1.png"));
        label17.setText("SPHL");
        label17.setToolTipText("");
        label17.setOpaque(true);
        label17.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label17);

        label18.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\uue_1.png"));
        label18.setText("UÜ");
        label18.setToolTipText("");
        label18.setOpaque(true);
        label18.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label18);

        label19.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\uuedls_1.png"));
        label19.setText("UÜDLS");
        label19.setToolTipText("");
        label19.setOpaque(true);
        label19.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label19);

        label20.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        label20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label20.setIcon(new javax.swing.ImageIcon("src\\main\\java\\resource\\ve_1.png"));
        label20.setText("VE");
        label20.setToolTipText("");
        label20.setOpaque(true);
        label20.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel3.add(label20);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jMenu2.setText("Bearbeiten");

        menustundenzeiten.setText("Stundenzeiten");
        menustundenzeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menustundenzeitenon_bearbeiten(evt);
            }
        });
        jMenu2.add(menustundenzeiten);

        menulehrerbea.setText("Lehrer");
        menulehrerbea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_lehrer(evt);
            }
        });
        jMenu2.add(menulehrerbea);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Datei");

        tabelleladen.setText("Tabelle laden");
        tabelleladen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelleladenActionPerformed(evt);
            }
        });
        jMenu3.add(tabelleladen);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void on_load(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_on_load
        data.Var.m.load();
    }//GEN-LAST:event_on_load

    private void Adden1Tabelle1adden(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adden1Tabelle1adden
        try {
            lehrerdlg = new LehrerDlg(null, true);
            if (lehrerdlg.isOk()) {
                lehrerdlg.setVisible(true);

            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_Adden1Tabelle1adden

    private void DeleteDeleteBestellung(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDeleteBestellung

    }//GEN-LAST:event_DeleteDeleteBestellung

    private void on_mouseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_on_mouseclicked
        if (klasseoderlehrer == false) {
            if (evt.getButton() == MouseEvent.BUTTON3) { 

                this.menutabelle1.show(this, evt.getX(), evt.getY());
            }

            if (evt.getButton() == MouseEvent.BUTTON1) {
                data.Var.klasseakt = list.getSelectedValue();
                BlTableLoad.akttable(data.Var.klasseakt);
            }
        } else if (klasseoderlehrer == true) {
            if (evt.getButton() == MouseEvent.BUTTON3) { 
                this.menutabelle2.show(this, evt.getX(), evt.getY());
            }

            if (evt.getButton() == MouseEvent.BUTTON1) {
                data.Var.lehrerakt = list.getSelectedValue();
                BlTableLoad.akttable(data.Var.lehrerakt);
            }

        }

    }//GEN-LAST:event_on_mouseclicked

    private void tabelleladenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelleladenActionPerformed
        bl.BlSavesAndLoads.laden();
        bl.BlSavesAndLoads.ladentimes();
        bl.BlSavesAndLoads.ladenteacher();
        bl.BlSavesAndLoads.ladenclass();
        data.Var.m.load();
    }//GEN-LAST:event_tabelleladenActionPerformed

    private void on_lehrer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_lehrer
        LehrerDllMain gui = new LehrerDllMain(null, true);
        gui.setVisible(true);
        gui.toFront();
    }//GEN-LAST:event_on_lehrer

    private void menustundenzeitenon_bearbeiten(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menustundenzeitenon_bearbeiten
        TimesDlg dialog = new TimesDlg(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

        if (TimesDlg.open == false) {
            data.Var.m.newtimes();
        }
    }//GEN-LAST:event_menustundenzeitenon_bearbeiten

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel3.setVisible(true);

        bl.BlPlan.enableTablebearbeiten(table);

        bl.BlPlan.enableLabelsbearbeiten(label);
        bl.BlPlan.enableLabelsbearbeiten(label2);
        bl.BlPlan.enableLabelsbearbeiten(label3);
        bl.BlPlan.enableLabelsbearbeiten(label4);
        bl.BlPlan.enableLabelsbearbeiten(label5);
        bl.BlPlan.enableLabelsbearbeiten(label9);
        bl.BlPlan.enableLabelsbearbeiten(label9);
        bl.BlPlan.enableLabelsbearbeiten(label11);
        bl.BlPlan.enableLabelsbearbeiten(label12);
        bl.BlPlan.enableLabelsbearbeiten(label13);
        bl.BlPlan.enableLabelsbearbeiten(label14);
        bl.BlPlan.enableLabelsbearbeiten(label15);
        bl.BlPlan.enableLabelsbearbeiten(label16);
        bl.BlPlan.enableLabelsbearbeiten(label17);
        bl.BlPlan.enableLabelsbearbeiten(label18);
        bl.BlPlan.enableLabelsbearbeiten(label19);
        bl.BlPlan.enableLabelsbearbeiten(label20);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        list.setModel(listenModellTeacher);
        Var.ansklasse = false;
        Var.anslehrer = true;
        klasseoderlehrer = false;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        list.setModel(listenModellClasse);
        Var.ansklasse = true;
        Var.anslehrer = false;
        klasseoderlehrer = true;

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bl.BlSavesAndLoads.speichern();
        bl.BlSavesAndLoads.speicherntimes();
        bl.BlSavesAndLoads.speichernteacher();
        bl.BlSavesAndLoads.speichernclass();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            table.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PlanDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Adden2Tabelle1adden(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adden2Tabelle1adden
        try {
            klassedlg = new KlasseDlg(null, true);
            if (klassedlg.isOk()) {
                klassedlg.setVisible(true);

            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_Adden2Tabelle1adden

    private void Delete1DeleteBestellung(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1DeleteBestellung
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete1DeleteBestellung

    //
    //
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlanDlg dialog = new PlanDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Adden1;
    private javax.swing.JMenuItem Adden2;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem Delete1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label20;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label9;
    private javax.swing.JList<String> list;
    private javax.swing.JMenuItem menulehrerbea;
    private javax.swing.JMenuItem menustundenzeiten;
    private javax.swing.JPopupMenu menutabelle1;
    private javax.swing.JPopupMenu menutabelle2;
    private javax.swing.JMenuItem tabelleladen;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
