/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.BlRefreshclassandteacher;
import data.Stunde;
import data.StundeBau;
import static gui.EntryDlg.modelcoml;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author timon_kaufmann
 */
public class StundeBauErstellenDlg extends javax.swing.JDialog {

    /**
     * Creates new form StundeBauErstellenDlg
     */
    public static DefaultComboBoxModel modelcomk = new DefaultComboBoxModel();
    private List<StundeBau> hour = new LinkedList<StundeBau>();

    public StundeBauErstellenDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        BlRefreshclassandteacher.refreshlistteacher();
        BlRefreshclassandteacher.refreshlistcombpclass();
        tfklasse.setModel(modelcomk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tfklasse = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        lbanz = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        jButton2.setText("GU-D");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_clickgud(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setText("BSP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_bsp(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setText("WE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_we(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setText("SPF");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_spf(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setText("DaZ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_daz(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setText("GU-M");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_gu_m(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton8.setText("RK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_rk(evt);
            }
        });
        jPanel3.add(jButton8);

        jButton9.setText("UÜ-GE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_uüge(evt);
            }
        });
        jPanel3.add(jButton9);

        jButton10.setText("FU");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_fu(evt);
            }
        });
        jPanel3.add(jButton10);

        jButton11.setText("SE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_se(evt);
            }
        });
        jPanel3.add(jButton11);

        jButton12.setText("GU-SU");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_gu_su(evt);
            }
        });
        jPanel3.add(jButton12);

        jButton13.setText("BE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_be(evt);
            }
        });
        jPanel3.add(jButton13);

        jButton14.setText("UÜ-Chor");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_uüchor(evt);
            }
        });
        jPanel3.add(jButton14);

        jButton15.setText("DF");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_df(evt);
            }
        });
        jPanel3.add(jButton15);

        jButton16.setText("GLZ");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_glz(evt);
            }
        });
        jPanel3.add(jButton16);

        jButton17.setText("GU-E");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_gu_e(evt);
            }
        });
        jPanel3.add(jButton17);

        jButton18.setText("ME");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_me(evt);
            }
        });
        jPanel3.add(jButton18);

        jButton19.setText("UÜ-DLS");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_uüdls(evt);
            }
        });
        jPanel3.add(jButton19);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.add(tfklasse);

        jButton1.setText("Einfügen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_ok(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        lbanz.setColumns(20);
        lbanz.setRows(5);
        scroll.setViewportView(lbanz);

        jPanel2.add(scroll);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void on_clickgud(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_clickgud
        hour.add(new StundeBau("GU-D", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "GU-D"+"\n");
    }//GEN-LAST:event_on_clickgud

    private void on_ok(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_ok
        for (StundeBau stundeBau : hour) {
            data.Var.bausteinelist.add(stundeBau);
        }
    }//GEN-LAST:event_on_ok

    private void on_gu_m(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_gu_m
        hour.add(new StundeBau("GU-M", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "GU-M"+"\n");
    }//GEN-LAST:event_on_gu_m

    private void on_gu_su(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_gu_su
        hour.add(new StundeBau("GU-SU", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "GU-SU"+"\n");
    }//GEN-LAST:event_on_gu_su

    private void on_gu_e(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_gu_e
        hour.add(new StundeBau("GU-E", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "GU-E"+"\n");
    }//GEN-LAST:event_on_gu_e

    private void on_bsp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_bsp
        hour.add(new StundeBau("BSP", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "BSP"+"\n");
    }//GEN-LAST:event_on_bsp

    private void on_rk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_rk
        hour.add(new StundeBau("RK", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "RK"+"\n");
    }//GEN-LAST:event_on_rk

    private void on_be(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_be
        hour.add(new StundeBau("BE", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "BE"+"\n");
    }//GEN-LAST:event_on_be

    private void on_me(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_me
        hour.add(new StundeBau("ME", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "ME"+"\n");
    }//GEN-LAST:event_on_me

    private void on_we(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_we
        hour.add(new StundeBau("WE", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "WE"+"\n");
    }//GEN-LAST:event_on_we

    private void on_uüge(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_uüge
        hour.add(new StundeBau("UÜ-GE", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "UÜ-GE"+"\n");
    }//GEN-LAST:event_on_uüge

    private void on_uüchor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_uüchor
        hour.add(new StundeBau("UÜ-Chor", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "UÜ-Chor"+"\n");
    }//GEN-LAST:event_on_uüchor

    private void on_uüdls(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_uüdls
        hour.add(new StundeBau("UÜ-DLS", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "UÜ-DLS"+"\n");
    }//GEN-LAST:event_on_uüdls

    private void on_spf(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_spf
        hour.add(new StundeBau("SPF", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "SPF"+"\n");
    }//GEN-LAST:event_on_spf

    private void on_fu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_fu
        hour.add(new StundeBau("FU", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "FU"+"\n");
    }//GEN-LAST:event_on_fu

    private void on_df(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_df
        hour.add(new StundeBau("DF", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "DF"+"\n");
    }//GEN-LAST:event_on_df

    private void on_daz(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_daz
        hour.add(new StundeBau("DAZ", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "DAZ"+"\n");
    }//GEN-LAST:event_on_daz

    private void on_se(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_se
        hour.add(new StundeBau("SE", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "SE"+"\n");
    }//GEN-LAST:event_on_se

    private void on_glz(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_glz
        hour.add(new StundeBau("GLZ", (String) tfklasse.getSelectedItem()));
        lbanz.append((String) tfklasse.getSelectedItem() + " " + "GLZ"+"\n");
    }//GEN-LAST:event_on_glz

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextArea lbanz;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JComboBox<String> tfklasse;
    // End of variables declaration//GEN-END:variables
}
