/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.BlRefreshclassandteacher;
import data.Lehrer;
import data.Stunde;
import data.StundeBau;
import static gui.EntryDlg.modelcoml;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author timon_kaufmann
 */
public class StundeBauErstellenDlg extends javax.swing.JDialog {

    /**
     * Creates new form StundeBauErstellenDlg
     */
    public static DefaultComboBoxModel modelcomk = new DefaultComboBoxModel();
    private List<StundeBau> hour = new LinkedList<StundeBau>();

    public StundeBauErstellenDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        BlRefreshclassandteacher.refreshlistteacher();
        BlRefreshclassandteacher.refreshlistteacher();
        BlRefreshclassandteacher.refreshlistcombpclass();
        tfklasse.setModel(modelcomk);
        tflehrer.setModel(modelcoml);
    }
    int anz = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tfklasse = new javax.swing.JComboBox<>();
        jButton20 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tflehrer = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        lbanz = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        jButton2.setText("GU-D");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_clickgud(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setText("BSP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_bsp(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setText("WE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_we(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setText("SPF");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_spf(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setText("DaZ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_daz(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setText("GU-M");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_gu_m(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton8.setText("RK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_rk(evt);
            }
        });
        jPanel3.add(jButton8);

        jButton9.setText("UÜ-GE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_uüge(evt);
            }
        });
        jPanel3.add(jButton9);

        jButton10.setText("FU");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_fu(evt);
            }
        });
        jPanel3.add(jButton10);

        jButton11.setText("SE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_se(evt);
            }
        });
        jPanel3.add(jButton11);

        jButton12.setText("GU-SU");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_gu_su(evt);
            }
        });
        jPanel3.add(jButton12);

        jButton13.setText("BE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_be(evt);
            }
        });
        jPanel3.add(jButton13);

        jButton14.setText("UÜ-Chor");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_uüchor(evt);
            }
        });
        jPanel3.add(jButton14);

        jButton15.setText("DF");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_df(evt);
            }
        });
        jPanel3.add(jButton15);

        jButton16.setText("GLZ");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_glz(evt);
            }
        });
        jPanel3.add(jButton16);

        jButton17.setText("GU-E");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_gu_e(evt);
            }
        });
        jPanel3.add(jButton17);

        jButton18.setText("ME");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_me(evt);
            }
        });
        jPanel3.add(jButton18);

        jButton19.setText("UÜ-DLS");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_uüdls(evt);
            }
        });
        jPanel3.add(jButton19);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.add(tfklasse);

        jButton20.setText("Zurück");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_back(evt);
            }
        });
        jPanel4.add(jButton20);

        jButton1.setText("Einfügen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_ok(evt);
            }
        });
        jPanel4.add(jButton1);

        tflehrer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(tflehrer);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        lbanz.setColumns(20);
        lbanz.setRows(5);
        scroll.setViewportView(lbanz);

        jPanel2.add(scroll);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refresh() {
        lbanz.setText("");
        for (StundeBau stundeBau : hour) {
            lbanz.append(stundeBau.getK() + " " + stundeBau.getStundenname() + " " + stundeBau.getL().getName() + "\n");
        }
    }

    private void on_clickgud(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_clickgud
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("GU-D", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_clickgud

    private void on_ok(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_ok
        for (StundeBau stundeBau : hour) {
            data.Var.bausteinelist.add(stundeBau);
        }
        data.Var.issafed = false;
        lbanz.setText("");
        hour.clear();
    }//GEN-LAST:event_on_ok

    private void on_gu_m(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_gu_m
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("GU-M", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_gu_m

    private void on_gu_su(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_gu_su
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("GU-SU", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_gu_su

    private void on_gu_e(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_gu_e
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("GU-E", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_gu_e

    private void on_bsp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_bsp
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("BSP", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_bsp

    private void on_rk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_rk
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("RK", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_rk

    private void on_be(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_be
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("BE", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_be

    private void on_me(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_me
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("ME", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_me

    private void on_we(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_we
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("WE", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_we

    private void on_uüge(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_uüge
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("UÜGE", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_uüge

    private void on_uüchor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_uüchor
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("UÜChor", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_uüchor

    private void on_uüdls(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_uüdls
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("UÜDLS", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_uüdls

    private void on_spf(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_spf
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("SPF", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_spf

    private void on_fu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_fu
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("FU", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_fu

    private void on_df(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_df
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("DF", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_df

    private void on_daz(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_daz
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("DAZ", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_daz

    private void on_se(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_se
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("SE", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_se

    private void on_glz(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_glz
        String kuerzel = null;
        boolean anwesend = false;
        for (Lehrer lehrer : data.Var.lehrer) {
            String comp = (String) tflehrer.getSelectedItem();
            if (comp.equalsIgnoreCase(lehrer.getName())) {
                kuerzel = lehrer.getKuerzel();
                anwesend = lehrer.isAnwesend();
            }
        }
        hour.add(new StundeBau("GLZ", (String) tfklasse.getSelectedItem(), new Lehrer((String) tflehrer.getSelectedItem(), kuerzel, anwesend)));
        refresh();
    }//GEN-LAST:event_on_glz

    private void on_back(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_back
        try {
            hour.remove(hour.size() - 1);
            refresh();
        } catch (IndexOutOfBoundsException e) {
        }

    }//GEN-LAST:event_on_back

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextArea lbanz;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JComboBox<String> tfklasse;
    private javax.swing.JComboBox<String> tflehrer;
    // End of variables declaration//GEN-END:variables
}
