/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Stunden;

/**
 *
 * @author lukas
 */
public class StundenDlg extends javax.swing.JDialog {

    /**
     * Creates new form StundenDlg
     */
    private int stunde;
    private String von;
    private Stunden stunden;
    private String bis;
    private boolean isOkay;

    public StundenDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        isOkay = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfstunde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfvon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfbis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Stunde:");
        getContentPane().add(jLabel1);
        getContentPane().add(tfstunde);

        jLabel2.setText("Von:");
        getContentPane().add(jLabel2);
        getContentPane().add(tfvon);

        jLabel3.setText("Bis:");
        getContentPane().add(jLabel3);
        getContentPane().add(tfbis);

        jButton1.setText("Hinzufügen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinufuegen(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("Abbrechen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hinufuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinufuegen
        try {
            stunde = Integer.parseInt(tfstunde.getText());
            von = tfvon.getText();
            bis = tfbis.getText();
            stunden = new Stunden(stunde, von, bis);
            isOkay = false;
            dispose();
        } catch (Exception e) {
            e.getMessage();
        }

    }//GEN-LAST:event_hinufuegen

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public String getVon() {
        return von;
    }

    public void setVon(String von) {
        this.von = von;
    }

    public String getBis() {
        return bis;
    }

    public void setBis(String bis) {
        this.bis = bis;
    }

    public boolean isIsOkay() {
        return isOkay;
    }

    public void setIsOkay(boolean isOkay) {
        this.isOkay = isOkay;
    }

    public Stunden getStunden() {
        return stunden;
    }

    public void setStunden(Stunden stunden) {
        this.stunden = stunden;
    }

    public void change(Stunden stund) {
        isOkay = true;
        this.tfstunde.setText(stund.getStunde() + "");
        this.tfvon.setText(stund.getVon());
        this.tfbis.setText(stund.getBis());
        this.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StundenDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StundenDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StundenDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StundenDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StundenDlg dialog = new StundenDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfbis;
    private javax.swing.JTextField tfstunde;
    private javax.swing.JTextField tfvon;
    // End of variables declaration//GEN-END:variables
}
